version: 1

disable_existing_loggers: False

formatters:
  detailed:
    format: "%(asctime)s - %(module)s:%(lineno)d - %(name)s - %(levelname)s - %(message)s"
  key_value:
    (): logfmter.Logfmter
    keys: [ "when", "at", "name", "module", "lineno" ]
    mapping:
      at: levelname
      when: asctime

handlers:
  console:
    class: logging.StreamHandler
    level: '${CONSOLE_LOG_LEVEL}'
    formatter: detailed
    stream: ext://sys.stdout
  console_kv:
    class: logging.StreamHandler
    level: '${CONSOLE_LOG_LEVEL}'
    formatter: key_value
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: '${FILE_LOG_LEVEL}'
    formatter: key_value
    filename: '${LOG_FILE_NAME}'
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf-8

loggers:
  uvicorn:
    level: INFO
    handlers: [ console, file ]
    propagate: no

root:
  level: DEBUG
  handlers: [ console, file ]