[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastflight"
authors = [{ name = "Chao Ning", email = "chao.ning.uk@gmail.com" }]
description = "FastAPI and Arrow Flight integrated server offering efficient dual-protocol support for both REST and gRPC data streaming."
version = "0.1.0"
readme = "README.md"
requires-python = ">= 3.11"
dependencies = [
    "email-validator",
    "fastapi[all]>=0.110.2",
    "pandas",
    "pyarrow>=14.0.0",
    "pydantic>=2.0",
    "structlog",
]

[project.optional-dependencies]
dev = [
    "jupyterlab",
    "nox",
    "pre-commit",
    "rich",
    "ruff",
    "uv",
]
test = ["pytest", "pytest-cov"]

[tool.ruff]
line-length = 120
src = ["src", "tests"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
# On top of the default `select` (`E4`, E7`, `E9`, and `F`), enable isort (`I`)
extend-select = ["I"]