[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = 'my_fastapi'
authors = [{ name = 'Chao Ning', email = 'chao.ning.uk@gmail.com' }]
description = 'My fastapi app'
version = '0.0.1'
readme = 'README.md'
requires-python = '>= 3.11'
dependencies = ['fastapi[all]==0.109.0', 'pydantic>=2.0', 'pandas']

[project.optional-dependencies]
dev = ['pre-commit', 'jupyterlab', 'ruff']
test = ['pytest', 'pytest-cov']

[tool.ruff.format]
skip-magic-trailing-comma = true