version: 1

disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s - %(module)s:%(lineno)d - %(name)s - %(levelname)s - %(message)s'

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers:
      - default
    propagate: no

root:
  level: DEBUG
  handlers:
    - default
  propagate: no